security:
    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        doctrine_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            anonymous: true
            pattern: ^/login
            stateless: true
            guard:
                authenticator: App\Security\Firewall\AdminAuthenticator
            provider: doctrine_user_provider

        restricted:
            pattern: ^/admin/(.*)
            stateless: true
            guard:
                authenticator: App\Security\Firewall\AdminAuthenticator
            provider: doctrine_user_provider

    access_control:
        - { path: ^/(.*), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
